project:
  type: book

book:
  title: "NIH"
  author: "Norah Jones"
  date: "2024/1/22"
  chapters:
    - index.qmd
    - intro.qmd
    - 2023_01_Book_Introduction of NIH-Common Fund.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

